name: Compile examples

on:
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"

  workflow_dispatch:

jobs:
  compile-parallel-examples:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        fqbn:
          - arduino:avr:uno
#           - arduino:avr:leonardo
#           - arduino:avr:mega:cpu=atmega2560

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}

          enable-deltas-report: true
          enable-warnings-report: true

          cli-compile-flags: |
            - --build-property
            - build.extra_flags=-DDisplayClass=LiquidCrystal -DLIQUIDMENU_LIBRARY=1
          sketch-paths: |
            - ./examples/A_hello_menu
            - ./examples/B_serial_menu
            - ./examples/C_functions_menu
            - ./examples/D_buttons_menu
            - ./examples/E_progmem_menu
            - ./examples/F_focus_menu
            - ./examples/G_glyph_menu
            - ./examples/H_system_menu
            - ./examples/J_scrolling_menu
            - ./examples/K_getters_menu
          libraries: |
            - source-path: ./
            - name: LiquidCrystal

      - name: Report
        uses: actions/upload-artifact@v2
        with:
          name: sketches-reports
          path: sketches-reports
        
  compile-i2c-examples:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        fqbn:
          - arduino:avr:uno
#           - arduino:avr:leonardo
#           - arduino:avr:mega:cpu=atmega2560

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}

          enable-deltas-report: true
          enable-warnings-report: true

          cli-compile-flags: |
            - --build-property
            - build.extra_flags=-DDisplayClass=LiquidCrystal_I2C -DLIQUIDMENU_LIBRARY=2
          sketch-paths: |
            - ./examples/I_I2C_menu
          libraries: |
            - source-path: ./
            - source-url: https://github.com/johnrickman/LiquidCrystal_I2C.git
            - name: LiquidCrystal
