name: Spell check

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Spell check
        uses: codespell-project/actions-codespell@master
        with:
          skip: ./doc/Doxygen/**,./doc/Doxygen/*
#          exclude_file: "./examples/E_progmem_menu/E_progmem_menu.ino"
          ignore_words_list: varius
